version: "3"
services:
  hub:
    image: selenium/hub:3.14
    ports:
      - "4444:4444"
  chrome:
    image: selenium/node-chrome:3.14
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  firefox:
    image: selenium/node-firefox:3.14
    shm_size: '1gb'
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  searchtesting1:
    image: sdabbiru/selenium-docker
    depends_on:
      - chrome
      - firefox
    environment:
      - HUB_HOST=hub
      - BROWSER=chrome
      - TESTSUITEFILE=searchtesting.xml
    volumes:
      - ./search-results1:/usr/share/udemy/test-output
  searchtesting2:
    image: sdabbiru/selenium-docker
    depends_on:
      - chrome
      - firefox
    environment:
      - HUB_HOST=hub
      - BROWSER=firefox
      - TESTSUITEFILE=searchtesting.xml
    volumes:
      - ./search-results2:/usr/share/udemy/test-output    

  bookflight1:
    image: sdabbiru/selenium-docker
    depends_on:
      - chrome
      - firefox
    environment:
      - HUB_HOST=hub
      - BROWSER=chrome
      - TESTSUITEFILE=bookflight.xml
    volumes:
      - ./book-results1:/usr/share/udemy/test-output
  bookflight2:
    image: sdabbiru/selenium-docker
    depends_on:
      - chrome
      - firefox
    environment:
      - HUB_HOST=hub
      - BROWSER=firefox
      - TESTSUITEFILE=bookflight.xml
    volumes:
      - ./book-results2:/usr/share/udemy/test-output  



